### ISSUE TITLE
Try/catch 

### ISSUE THREAD

**Issue by siriocra** [nicolas-ivanov/Rino#5]
Catch exceptions from Android. Make a pop-up window.

**Comment by nicolas-ivanov** [comment]
Ira,
I have fixed a bug with app crashing after recognition process is cancelled.
However, it was not connected with exceptions, since recognition application does not throw one when it is cancelled.
Istead, it returns a result Intent with resultCode = RESULT_CANCELLED.
This case was not handled in SpeakButton.OnActivityResult, so it led to crashing.

Thus no try/catch block was added, and it seems to me we don't need any so far.

**Comment by siriocra** [comment]
I have no problems with it either, so I close the issue
